config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users, controllers:{
  sessions: 'users/sessions',
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations'

}

  root 'welcome#index'
  resources  :documents
  resources  :employees
  # Public pages routes
  get 'about' => 'page#about_us'
  get 'contact' => 'page#contact_us'
  get 'privacy-policy' => 'page#privacy_policy'
  get 'term-and-condition' => 'page#Term_and_condition'
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :documents
	validates :first_name,:last_name,presence:true
	validates :email,presence:true,uniqueness:true
	validates :city,:pincode,:address,presence:true

	def name
		"#{first_name} #{last_name}".strip
	end

	def full_address
		"#{city} #{pincode} #{address}".strip
	end

	def name_with_email
		"#{name} (#{email})"
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_employee, only: [:edit,:update,:show,:destroy]

	def index
		@employee = Employee.all
	end

	def new
		@employee = Employee.new
		end

	def create
		 @employee = Employee.new(employee_params)
		 if @employee.save
		 	CurdNotificationMailer.create_notification(@employee).deliver_now
		 	redirect_to employees_path,notice: "Employee has been created sucessfully"
		 else
		 	render :new
		 end
	end  

	def edit
	end

	def update
		if @employee.update(employee_params)
			CurdNotificationMailer.update_notification(@employee).deliver_now
			redirect_to employees_path,notice: "Employee has been updated sucessfully"
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		CurdNotificationMailer.delete_notification(@employee).deliver_now
		if @employee.destroy
			redirect_to employees_path,notice: "Employee has benn deleted Sucessfully"
		end
	end

	private

	def employee_params
		params.require(:employee).permit(:first_name,:last_name,:email,
			:age,:date_of_birth,:city,:pincode,:address,:contact_no)
	end

	def set_employee
		@employee = Employee.find(params[:id])
	rescue ActiveRecord::RecordNotFound => error
		redirect_to employees_path,notice: error
	end
end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form|%>
    <div class="row">

	<!-- 	<%# if @employee.errors.any?%>
	<div class="col-lg-12">
        <p class="lead">Please fix errors below</p>
        <%# @employee.errors.full_messages.each do |message|%>
        <p class="text-danger"><%#= message%></p>
        <%# end%>
	</div>
	<%# end %> -->



	<div class="col-lg-4">
		<div class="form-group">
			<%= form.label :first_name,class: "mb-2 mt-3"%>
			<%= form.text_field :first_name,placeholder:"First Name", class: "form-control form-control-lg rounded-0"%>
			<% @employee.errors.full_messages_for(:first_name).each do |message|%>
			<p class="text-danger"><%= message%></p>
			<% end %>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="form-group">
			<%= form.label :last_name,class: "mb-2 mt-3"%>
			<%= form.text_field :last_name,placeholder:"Last Name", class: "form-control form-control-lg rounded-0"%>
			<% @employee.errors.full_messages_for(:last_name).each do |message|%>
			<p class="text-danger"><%= message%></p>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-6">
			<div class="form-group">
				<%= form.label :email,class: "mb-2"%>
				<%= form.text_field :email,placeholder:"Email", class: "form-control form-control-lg rounded-0"%>
				<% @employee.errors.full_messages_for(:email).each do |message|%>
				<p class="text-danger"><%= message%></p>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :date_of_birth,class: "mb-2"%>
					<%= form.date_field :date_of_birth, class: "form-control form-control-lg rounded-0"%>
					<% @employee.errors.full_messages_for(:date_of_birth).each do |message|%>
					<p class="text-danger"><%= message%></p>
					<% end %>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :age,class: "mb-2"%>
					<%= form.number_field :age,placeholder:"Age", class: "form-control form-control-lg rounded-0"%>

				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :city,class: "mb-2"%>
					<%= form.text_field :city,placeholder:"City", class: "form-control form-control-lg rounded-0"%>
					<% @employee.errors.full_messages_for(:city).each do |message|%>
					<p class="text-danger"><%= message%></p>
					<% end %>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :pincode,class: "mb-2"%>
					<%= form.text_field :pincode,placeholder:"Pincode", class: "form-control form-control-lg rounded-0"%>
					<% @employee.errors.full_messages_for(:pincode).each do |message|%>
					<p class="text-danger"><%= message%></p>
					<% end %>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-8">
					<div class="form-group">
						<%= form.label :address,class: "mb-2"%>
						<%= form.text_field :address,placeholder:"Address", class: "form-control form-control-lg rounded-0"%>
						<% @employee.errors.full_messages_for(:address).each do |message|%>
						<p class="text-danger"><%= message%></p>
						<% end %>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-4">
						<div class="form-group">
							<%= form.label :contact_no,class: "mb-2"%>
							<%= form.text_field :contact_no,placeholder:"Contact No", class: "form-control form-control-lg rounded-0"%>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<%= form.submit class: "btn btn-info rounded-0 mt-3 mb-3"%>
								<%= link_to "Back to Employee",employees_path,class:"btn btn-outline-info rounded-0 mt-3 mb-3"%>

							</div>
						</div>
					</div>
				</div>
<% end %>

app/views/employees/edit.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center">Edit Employee Information</h2>
		</div>
	</div>

	<%= render "form",employee: @employee %>
</div>




	
		

app/views/employees/index.html.erb
<div class="col-lg-12">
	<%= flash[:notice]%>
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center">Listing Employees</h2>
		</div>
	</div>
	<%= link_to "Create New Employee",new_employee_path,class:"btn btn-info rounded-0 mt-4"%>
	<div class="dropdown">
		<button class="btn btn-secondary dropdown-toggle mt-3 rounded-0" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
			View List In
		</button>
		<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<li><%= link_to "Table",employees_path(view_type: 'table'),class:" dropdown-item"%></li>
			<li><%= link_to "Accordian",employees_path(view_type: 'accordian'),class:" dropdown-item"%></li>
		</ul>
	</div>
	<% if params[:view_type] != "accordian"%>
	<table class="table table-info table-bordered mt-2">
		<thead>
			<tr>
				<th>Name</th>
				<th>Eamil</th>
				<th>Age</th>
				<th>Date of _Birth</th>
				<th> Full Address</th>
				<th>Contact No</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @employee.each do |employee|%>
			<tr>
				<td><%= employee.name%></td>
				<td><%= employee.email%></td>
				<td><%= employee.age%></td>
				<td><%= employee.date_of_birth%></td>
				<td><%= employee.full_address%></td>
				<td><%= employee.contact_no%></td>
				<td>

					<div class="dropdown">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
							Actions
						</button>

						<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							<li><%= link_to "Edit",edit_employee_path(employee),class:" dropdown-item"%></li>
							<li><%= link_to "View",employee_path(employee),class:"dropdown-item"%></li>
							<li><%= link_to "Delete",employee_path(employee),class:"dropdown-item",method: :delete,data:{confirm:"Are you sure you, want to delete this record ?"}%>

							</li>
						</ul>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>

	<% if params[:view_type].present? && params[:view_type] == "accordian"%>


	<div class="accordion" id="accordionExample">
		<% @employee.each do |employee|%>
		<div class="accordion-item">
			<h2 class="accordion-header" id="heading_<%= employee.id%>">
				<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= employee.id%>" aria-expanded="true" aria-controls="collapse_<%= employee.id%>">
					<%= employee.name_with_email %>
				</button>
			</h2>
			<div id="collapse_<%= employee.id%>" class="accordion-collapse collapse " aria-labelledby="heading_<%= employee.id%>" data-bs-parent="#accordionExample">
				<div class="accordion-body">
					<h2 class="text-center mb-5">Employee Detail</h2>
					<div class="row mt-5">
						<div class="col-lg-6">
							<h3 class="mb-3">Personal Information</h3>
							<p class="lead"><strong>First Name :</strong><%= employee.first_name %></p>
							<p class="lead"><strong>last Name :</strong><%= employee.last_name %></p>
							<p class="lead"><strong>Email :</strong><%= employee.email %></p>
							<p class="lead"><strong>Age :</strong><%= employee.age %></p>
							<p class="lead"><strong>Date of Birth :</strong><%= employee.date_of_birth%></p>
						</div>
						<div class="col-lg-6">
							<h3 class="mb-3">Address Information</h3>
							<p class="lead"><strong>City :</strong><%= employee.city %></p>
							<p class="lead"><strong>Pincode :</strong><%= employee.pincode %></p>
							<p class="lead"><strong>Address :</strong><%= employee.address %></p>
							<p class="lead"><strong>Contact No :</strong><%= employee.contact_no%></p>
						</div>
						<div class="col-lg-12">

							<%= link_to "Edit",edit_employee_path(employee),class:"btn btn-info rounded-0"%>
							<%= link_to "Delete",employee_path(employee),class:"btn btn-danger rounded-0",method: :delete,data:{confirm:"Are you sure you, want to delete this record ?"}%>
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div>
		<% end %>
	</div>


	

app/views/employees/new.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center">New Employee</h2>
		</div>
	</div>

	<%= render "form",employee: @employee %>

	</div>



	
		

app/views/employees/show.html.erb
<div class="col-lg-10">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center mb-5">Employee Detail</h2>
			<div class="row mt-5">
				<div class="col-lg-6">
					<h3 class="mb-3">Personal Information</h3>
					<p class="lead"><strong>First Name :</strong><%= @employee.first_name %></p>
					<p class="lead"><strong>last Name :</strong><%= @employee.last_name %></p>
					<p class="lead"><strong>Email :</strong><%= @employee.email %></p>
					<p class="lead"><strong>Age :</strong><%= @employee.age %></p>
					<p class="lead"><strong>Date of Birth :</strong><%= @employee.date_of_birth%></p>
				</div>
				<div class="col-lg-6">
					<h3 class="mb-3">Address Information</h3>
					<p class="lead"><strong>City :</strong><%= @employee.city %></p>
					<p class="lead"><strong>Pincode :</strong><%= @employee.pincode %></p>
					<p class="lead"><strong>Address :</strong><%= @employee.address %></p>
					<p class="lead"><strong>Contact No :</strong><%= @employee.contact_no%></p>
				</div>

				<% if @employee.documents.present? %>
				<div class="row mt-5">
					<h2 class="text-center mb-5">Employee Documents</h2>
					<% @employee.documents.each do |document|%>
					<div class="card">
						<div class="card-body">
							<div class="row">
									<% if document.image.attached? %>
								<div class="col-lg-4">
					                  <%= image_tag document.image,class:"img-fluid" %>
								</div>
					                  <% end %>                  
								<div class="col-lg-4">
									<p class="lead"><%= document.name %></p>
								</div>
								<div class="col-lg-4">
									<p class="lead"><%= document.doc_type%></p>
								</div>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			<%end%>
			</div>
			
			<%= link_to "Edit Employee",edit_employee_path(@employee),class:"btn btn-info rounded-0 mt-3 mb-3"%>
			<%= link_to "Back to Employee",employees_path,class:"btn btn-outline-info rounded-0 mt-3 mb-3"%>
		</div>
	</div>
</div>


				