config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users, controllers:{
  sessions: 'users/sessions',
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations'

}

  root 'welcome#index'
  resources  :documents
  resources  :employees
  # Public pages routes
  get 'about' => 'page#about_us'
  get 'contact' => 'page#contact_us'
  get 'privacy-policy' => 'page#privacy_policy'
  get 'term-and-condition' => 'page#Term_and_condition'
end

app/views/shared/_dummy_content.html.erb
<div class="col-lg-10 mx-auto">
	
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-body-info">Place sticky footer content here.</span>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <%= link_to "HR-Mitra",root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="javascript:void(0)">signed in as <%= current_user.email %></a></li>
            <li><%= link_to 'Sign Out',destroy_user_session_path,class:"dropdown-item", method: :delete,data:{confirm:"If you logout, your current session will be destroyed. Are you sure you want to logout?"}%></li>
            
          </ul>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In',new_user_session_path,class:"nav-link"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<%= link_to 'About Us',about_path,target:"_blank",style:"color:red;" %>
<%= link_to 'Contact Us',contact_path,target:"_blank" ,style:"color:red;"%>
<%= link_to 'Privacy-Policy',privacy_policy_path,target:"_blank" ,style:"color:red;"%>
<%= link_to 'Term-and-Condition',term_and_condition_path,target:"_blank" ,style:"color:red;"%>