config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users, controllers:{
  sessions: 'users/sessions',
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  confirmations: 'users/confirmations'

}

  root 'welcome#index'
  resources  :documents
  resources  :employees
  # Public pages routes
  get 'about' => 'page#about_us'
  get 'contact' => 'page#contact_us'
  get 'privacy-policy' => 'page#privacy_policy'
  get 'term-and-condition' => 'page#Term_and_condition'
end

app/models/document.rb
class Document < ApplicationRecord

  DOC_TYPES = ['Markssheet','Photo ID','Address Proof','Personal ID','Other'].freeze
  
  belongs_to :employee

  has_one_attached :image

  validates :name, :doc_type, presence:true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :set_document, only: [:edit,:update,:show,:destroy]

	def index
		@document = Document.all
	end

	def new
		@document = Document.new
		end

	def create
		 @document = Document.new(document_params)
		 if @document.save
		 	redirect_to documents_path,notice: "Document has been created sucessfully"
		 else
		 	render :new
		 end
	end  

	def edit
	end

	def update
		if @document.update(document_params)
			redirect_to documents_path,notice: "Document has been updated sucessfully"
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		if @document.destroy
			redirect_to documents_path,notice: "Document has been deleted Sucessfully"
		end
	end

	private

	def document_params
		params.require(:document).permit(:name,:doc_type,:employee_id,:image)
	end

	def set_document
		@document = Document.find(params[:id])
	rescue ActiveRecord::RecordNotFound => error
		redirect_to documents_path,notice: error
	end
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form| %>  
  <div class="row">
	  <div class="col-lg-4">
		  <div class="form-group">
			  <%= form.label :name,class: "mb-2 mt-3"%>
			  <%= form.text_field :name,placeholder:"Name", class: "form-control form-control-lg rounded-0"%>
			  <% @document.errors.full_messages_for(:name).each do |message|%>
			  <p class="text-danger"><%= message%></p>
			  <% end %>
		  </div>

		  <div class="form-group">
			  <%= form.label :doc_type,class: "mb-2 mt-3"%>
			  <%= form.select :doc_type, options_for_select(Document::DOC_TYPES,selected: document.doc_type),{prompt: "Select Document Type"}, {class: "form-select form-select-lg rounded-0"} %>
			  <% @document.errors.full_messages_for(:doc_type).each do |message|%>
			  <p class="text-danger"><%= message%></p>
			  <% end %>
		  </div>
		  <div class="form-group">
			  <%= form.label :employee_id,class: "mb-2 mt-3"%>
			  <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name_with_email,employee.id]},selected: document.employee_id),{prompt: "Select employee"}, {class: "form-select form-select-lg rounded-0"} %>
			  <%#= form.select :employee_id, options_for_select(Employee.pluck(:first_name,:id),selected: document.employee_id),{prompt: "Select employee"}, {class: "form-select form-select-lg rounded-0"} %>
			  <% @document.errors.full_messages_for(:employee_id).each do |message|%>
			  <p class="text-danger"><%= message%></p>
			  <% end %>
		  </div>
		  <div class="form-group">
		  	<%= form.label :image, class:"mb-2 mt-2" %><br>
		  	<%= form.file_field :image%>
	  </div>
	  <div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.submit class: "btn btn-info rounded-0 mt-3 mb-3"%>
					<%= link_to "Back to Document",documents_path,class:"btn btn-outline-info rounded-0 mt-3 mb-3"%>
				</div>
			</div>
       </div>
<% end %>

app/views/documents/edit.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center">Edit Document</h2>
		</div>
	</div>

	<%= render "form",document: @document %>

	</div>

app/views/documents/index.html.erb
<div class="col-lg-10">
	<%= flash[:notice]%>
<div class="card rounded-0 mt-5">
	<div class="card-body">
		<h2 class="text-center">Listing Documents</h2>
	</div>
</div>
<%= link_to "Create New Document",new_document_path,class:"btn btn-info rounded-0 mt-4"%>
<table class="table table-info table-bordered mt-4">
	<thead>
		<tr>
			<th>Name</th>
			<th>Doc_type</th>
			<th>Employee</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @document.each do |document|%>
		<tr>
			<td><%= document.name%></td>
			<td><%= document.doc_type%></td>
			<td><%= link_to document.employee.name, employee_path(document.employee),class:"btn btn-outline-dark rounded-0"%></td>
			<td>

				<div class="dropdown">
					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
						Actions
					</button>

					<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						<li><%= link_to "Edit",edit_document_path(document),class:" dropdown-item"%></li>
						<li><%= link_to "View",document_path(document),class:"dropdown-item"%></li>
						<li><%= link_to "Delete",document_path(document),class:"dropdown-item",method: :delete,data:{confirm:"Are you sure you, want to delete this record ?"}%>
							
						</li>
					</ul>
				</div>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center">Create New Document</h2>
		</div>
	</div>

	<%= render "form",document: @document %>

	</div>

app/views/documents/show.html.erb
<div class="col-lg-10">
	<div class="card rounded-0 mt-5">
		<div class="card-body">
			<h2 class="text-center mb-5">Document Detail</h2>
			<div class="row mt-5">
				<div class="col-lg-6">
					<% if @document.image.attached? %>
					<%= image_tag @document.image %>
					<% end %>
					<p class="lead"><strong> Name :</strong><%= @document.name %></p>
					<p class="lead"><strong>Doc Type :</strong><%= @document.doc_type %></p>
					<p class="lead"><strong>Document Id :</strong><%= @document.employee_id %></p>
				</div>
			</div>
			<%= link_to "Edit Document",edit_document_path(@document),class:"btn btn-info rounded-0 mt-3 mb-3"%>
			<%= link_to "Back to Document",documents_path,class:"btn btn-outline-info rounded-0 mt-3 mb-3"%>
		</div>
	</div>
</div>